"use strict";
// import React, { useState } from 'react';
// import {
//   useAppDispatch,
//   useAppSelector,
// } from '../src/app/hooks';
// import {
//   decrement,
//   increment,
//   incrementByAmount,
//   selectCount,
// } from '../src/features/counter';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
// const IndexPage:React.FC = () => {
//   const dispatch = useAppDispatch();
//   const count = useAppSelector(selectCount);
//   const [incrementAmount, setIncrementAmount] = useState<number>(0);
//   return (
//     <>
//       <h1>Welcome to the greatest app in the world!</h1>
//       <h2>
//         The current number is
//         {count}
//       </h2>
//       <div>
//         <input
//           value={incrementAmount}
//           onChange={(e) => setIncrementAmount(Number(e.target.value))}
//           type="number"
//         />
//         <button
//           onClick={() => dispatch(incrementByAmount(Number(incrementAmount)))}
//         >
//           Increment by amount
//         </button>
//       </div>
//       <div>
//         <button onClick={() => dispatch(decrement())}>Decrement by 1</button>
//         <button onClick={() => dispatch(increment())}>Increment by 1</button>
//       </div>
//     </>
//   );
// };
// export default IndexPage;
const head_1 = __importDefault(require("next/head"));
const Login_1 = __importDefault(require("../src/features/screens/Login/Login"));
const Home_module_css_1 = __importDefault(require("../styles/Home.module.css"));
function login() {
    return (<div className={Home_module_css_1.default.container}>
      <head_1.default>
        <title>cashingames About</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </head_1.default>
      <main>
        <Login_1.default />
      </main>
    </div>);
}
exports.default = login;
