import Head from 'next/head'
import Image from 'next/image'
import SignUpProfile from '../src/features/screens/SignUpProfile/SignUpProfile'
import styles from '../styles/Home.module.css'

export default function signup() {
  return (
    <div className={styles.container}>
      <Head>
        <title>cashingames About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignUpProfile />
      </main>
    </div>
  )
}