"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const head_1 = __importDefault(require("next/head"));
const SignUpProfile_1 = __importDefault(require("../src/features/screens/SignUpProfile/SignUpProfile"));
const Home_module_css_1 = __importDefault(require("../styles/Home.module.css"));
function signupprofile() {
    return (<div className={Home_module_css_1.default.container}>
      <head_1.default>
        <title>cashingames About</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </head_1.default>
      <main>
        <SignUpProfile_1.default />
      </main>
    </div>);
}
exports.default = signupprofile;
