name: Staging pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn run build --if-present
        env:
          CI: true
          REACT_APP_API_URL: https://stg-api.cashingames.com/api
          REACT_APP_API_ROOT_URL: https://stg-api.cashingames.com
          REACT_APP_URL: https://stg.cashingames.com
          REACT_APP_PAYSTACK_KEY: ${{secrets.PAYSTACK_KEY_TEST}}
          REACT_APP_GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          REACT_APP_FIREBASE_API_KEY: ${{secrets.STAGING_FIREBASE_API_KEY}}
          REACT_APP_FIREBASE_APP_ID: ${{secrets.STAGING_FIREBASE_APP_ID}}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.STAGING_FIREBASE_MEASUREMENT_ID}}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.STAGING_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.STAGING_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.STAGING_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.STAGING_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FACEBOOK_CLIENT_ID: ${{secrets.STAGING_FACEBOOK_CLIENT_ID}}
          REACT_APP_BRAND_ID: 2
          REACT_APP_REQUEST_ENV: stake-testing
      # - name: cypress test
      #   run: |
      #     npm run cypress-test

      - name: cd - deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.STG_FTP_USERNAME }}
          password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: ./build/
