name: Staging pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn run build --if-present
        env:
          CI: true
          REACT_APP_API_URL: https://stg-api.cashingames.com/api
          REACT_APP_API_ROOT_URL: https://stg-api.cashingames.com
          REACT_APP_URL: https://stg.cashingames.com
          REACT_APP_PAYSTACK_KEY: ${{ secrets.PAYSTACK_KEY_TEST }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}


      # - name: cypress test
      #   run: |
      #     npm run cypress-test

      - name: cd - deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.STG_FTP_USERNAME }}
          password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: ./build/
